네이버 맵 마커 / 하단 ViewPager 추가 (임시 데이터)
boostcampwm-2022/android04-BEEP pull request #41
Opened 2022-11-14 16:50 UTC by lee-ji-hoon

resolved: #15 

## 작업 내용

> 어떤 작업을 했는지 적어주세요!

## 체크리스트
- [ ] Assignees 설정
- [ ] Labels 설정
- [ ] Projects 설정
- [ ] Milestone 설정

## 동작 화면

> 존재하지 않는다면 패스해주세요!

2022-11-14 16:59 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/binding/TextBindingAdapter.kt
> +}
이렇게 D-day 설정을 BindingAdapter로 빼봤는데 어떻게들 생각하시는지 궁금합니다!

2022-11-14 18:32 UTC, mangbaam commented on presentation/src/main/java/com/lighthouse/presentation/binding/TextBindingAdapter.kt
> +}
우리 프로젝트에서 범용적으로 사용될 것 같아서 좋습니다

2022-11-14 18:41 UTC, mangbaam requested changes

2022-11-14 18:41 UTC, mangbaam commented on presentation/src/main/java/com/lighthouse/presentation/binding/TextBindingAdapter.kt
> +}
사소한거지만 이 부분은 strings 로 빼는 것이 더 좋을 것 같아요
이유는 나라마다 년/월/일 표기법이 달라서인데
꼭 수정되어야 할 부분은 아닌 것 같습니다

2022-11-14 18:41 UTC, mangbaam commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/FusedLocationProvider.kt
> +        if (ActivityCompat.checkSelfPermission(
KDoc 사용도 고려해보세용 😎

2022-11-14 18:41 UTC, mangbaam commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/MapActivity.kt
> +        )
UUID 만드는 부분 제가 유틸로 만들어놔서 나중에 머지되면 사용해주시면 될 것 같아요

2022-11-14 18:41 UTC, mangbaam commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/MapActivity.kt
> +    }
큰 차이가 있을 지는 모르겠지만 컴포넌트를 정리하는 코드가 `super`  코드보다 위에 위치하면 더 좋을 것 같아요

2022-11-14 18:41 UTC, mangbaam commented on presentation/src/main/res/layout/activity_map.xml
> +            android:overScrollMode="never"
`vp_gifticon` 네이밍이 저희 컨벤션에 맞을 것 같아요

2022-11-15 02:24 UTC, yangsooplus commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/FusedLocationProvider.kt
> +    }
가장 최근의 location을 들고 오는 것인데 콜백으로 하나 보내고 for문을 break 하고 있는데, 이거 꼭 for문에서 실행되어야만 하는 코드인가요??

2022-11-15 02:25 UTC, audxo112 approved these changes

2022-11-15 02:51 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/FusedLocationProvider.kt
> +    }
아닙니다.. 제가 이 부분을 먼저 구현을 하고 내부 코드 보다가 lastLocation을 발견하고 아래에는 적용을 했는데 해당 부분을 놓치고 있었네요! 바로 아래 처럼 고쳐놨습니다 👍 

```kotlin
private fun setLocationCallback() {
    locationCallback = object : LocationCallback() {
        override fun onLocationResult(locationResult: LocationResult) {
            locationResult.lastLocation?.let { listener.onLocationUpdated(it) }
        }
    }
}
```

2022-11-15 02:51 UTC, lee-ji-hoon commented on presentation/src/main/res/layout/activity_map.xml
> +            android:overScrollMode="never"
맞네요 vp로 해도 딱히 겹치는 얘들도 없고하니 고쳐두겠습니다!

2022-11-15 02:51 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/MapActivity.kt
> +    }
바로 해결해뒀습니다 :)

2022-11-15 02:51 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/FusedLocationProvider.kt
> +        if (ActivityCompat.checkSelfPermission(
KDoc 사용이라면 TODO에는 나중에 추가적인 작업이 필요한 것이 있으면 적는 곳이라고 생각을 해서 아래처럼 설명만 적을때는 이렇게 사용을 하면 될까요?

<img width="209" alt="image" src="https://user-images.githubusercontent.com/53300830/201813986-a292023f-6c9b-4a38-89a4-d7d4c3036272.png">

> TODO KDoc 사용 예시
<img width="595" alt="image" src="https://user-images.githubusercontent.com/53300830/201814135-a2aba794-9b8c-4a58-a22f-a46430d44c0e.png">

2022-11-15 02:51 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/MapActivity.kt
> +        )
아 맞다 이거 안그래도 여쭤볼려고 했는데 안올린거 같아서 임시로 사용했었어서 바로 적용해둘게요!

2022-11-15 02:51 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/binding/TextBindingAdapter.kt
> +}
strings로 빼는걸 저도 고려하고 있었는데 Date 객체다보니 parsing 하는 로직쪽을 변경해야 될까요?

```kotlin
@BindingAdapter("setExportedDate")
fun setExportedDate(view: TextView, date: Date) {
    view.text = date.toString("~ yyyy-MM-dd")
}

// 여기 부분이 Date를 제가 원하는 foramt으로 바꾸는 부분입니다!
private fun Date.toString(format: String): String {
    val dateFormatter = SimpleDateFormat(format, Locale.getDefault())
    return dateFormatter.format(this)
}
```

2022-11-15 02:53 UTC, yangsooplus commented on presentation/src/main/java/com/lighthouse/presentation/ui/map/FusedLocationProvider.kt
> +    }
캬하 양수진 드디어 제대로된 리뷰 하나 했다 감격

2022-11-15 06:14 UTC, lee-ji-hoon commented on presentation/src/main/java/com/lighthouse/presentation/binding/TextBindingAdapter.kt
> +}
<img width="289" alt="image" src="https://user-images.githubusercontent.com/53300830/201840404-97416a55-3fec-4486-8be3-e48d6061b8fb.png">

2022-11-15 06:16 UTC, mangbaam approved these changes

2022-11-15 06:26 UTC, merged