PIN UI 관련 작업
boostcampwm-2022/android04-BEEP pull request #87
Opened 2022-11-21 17:43 UTC by yangsooplus

resolved: #84 

## 작업 내용

- PIN 프래그먼트 레이아웃 구성
- PIN 입력/확인/불일치/사용 안 함에 따라 UI 상태 설정
- 액티비티/프래그먼트 이동
- 이제 PIN과 설정 정보를 저장하는 작업을 해야 함

## 체크리스트
- [x] Assignees 설정
- [x] Labels 설정
- [x] Projects 설정
- [x] Milestone 설정

## 동작 화면

![pin](https://user-images.githubusercontent.com/69582122/203123997-8d8fefe5-8a18-4816-a7fb-fa84f430968e.gif)

2022-11-21 18:01 UTC, lee-ji-hoon requested changes

2022-11-22 06:30 UTC, yangsooplus commented on presentation/src/main/java/com/lighthouse/presentation/ui/security/pin/PinViewModel.kt
> +    }
PIN을 String으로 관리하기 때문에
"12345" 에서 백스페이스로 지우면 "1234" 가 되도록 마지막 하나 빼고 잘라줬습니다

2022-11-22 06:55 UTC, mangbaam commented on presentation/src/main/java/com/lighthouse/presentation/ui/security/pin/PinViewModel.kt
> +    }
```suggestion
    fun removePin() {
        if (pinString.value.isNotEmpty()) {
            _pinString.update { pinString.value.dropLast(1) }
        }
    }
```

이렇게는 어떤가요?

2022-11-22 06:57 UTC, audxo112 commented on presentation/src/main/java/com/lighthouse/presentation/ui/security/pin/PinFragment.kt
> +                    PinSettingType.COMPLETE -> (requireActivity() as SecurityActivity).moveScreen(SecurityDirections.FINGERPRINT)
activityViewModels 를 이용하여 이벤트를 이용해 보는건 어떨까요

2022-11-22 07:09 UTC, mangbaam requested changes

2022-11-22 07:09 UTC, mangbaam commented on presentation/src/main/res/layout/fragment_pin.xml
> +            app:layout_constraintEnd_toStartOf="@+id/iv_pin_1"
해보진 않아서 될 지 모르겠는데 selector 로 두 상태를 담는 xml 파일을 만들고 상태를 변경하면서 drawable 의 모양을 바꿔주는 방식은 어떤가요?

2022-11-22 07:09 UTC, mangbaam commented on presentation/src/main/res/layout/fragment_pin.xml
> +            app:layout_constraintVertical_chainStyle="packed" />
밑에 키패드용 TextView 에 모두 bias 0.5 가 설정된 이유가 무엇일까요? consraint 를 잘 걸어주는 것만으로도 구현가능한 부분같아요

2022-11-22 07:09 UTC, mangbaam commented on presentation/src/main/res/layout/fragment_pin.xml
> +            app:layout_constraintGuide_percent="0.4" />
밑에 완료 버튼을 없앤다면 이 가이드도 없애고 키패드 위치는 바닥에 붙인 후 marginBottom 을 살짝 주면 될 것 같네요

2022-11-22 09:00 UTC, yangsooplus commented on presentation/src/main/java/com/lighthouse/presentation/ui/security/pin/PinViewModel.kt
> +    }
아.... 맞다... dropLast가 있었군요..

2022-11-22 09:03 UTC, yangsooplus commented on presentation/src/main/java/com/lighthouse/presentation/ui/security/pin/PinViewModel.kt
> +                temporaryPinString = pinString.value
`temporaryPinString` 는 정말 말 그대로 임시로 설정한 pin을 가지고 있는 변수여서 그렇게 이름을 지었는데 명확하지 못한가요?? `next()`은 `goNextStep()`으로 바꿔주었습니다 :ㅇ

2022-11-22 09:05 UTC, yangsooplus commented on presentation/src/main/res/layout/fragment_pin.xml
> +            app:layout_constraintVertical_chainStyle="packed" />
desgin 탭에서 chain을 걸어줄 때 자동으로 생성되어서 필요할 줄 알았는데 빼줘도 의도한대로 잘 나오네요

2022-11-22 09:56 UTC, yangsooplus commented on presentation/src/main/res/layout/fragment_pin.xml
> +            app:layout_constraintEnd_toStartOf="@+id/iv_pin_1"
이거 해보려고 selector까지 만들어서 해봤는데 오히려 더 복잡해진 느낌이라 기존 것을 유지했습니다

2022-11-22 14:40 UTC, yangsooplus commented on presentation/src/main/java/com/lighthouse/presentation/ui/security/pin/PinFragment.kt
> +                    PinSettingType.COMPLETE -> (requireActivity() as SecurityActivity).moveScreen(SecurityDirections.FINGERPRINT)
Main 쪽을 참고해서 수정해봤습니다

2022-11-22 14:42 UTC, lee-ji-hoon approved these changes

2022-11-22 14:44 UTC, mangbaam approved these changes

2022-11-22 14:53 UTC, merged